name: Auto Protect Repo

on:
  schedule:
    - cron: "0 */6 * * *"  # cek tiap 6 jam
  workflow_dispatch:

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install PyGithub requests

      - name: Run protect script
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
        run: python tools/protect_repo.py
